#Copia do 03_02 pois neste possui o print funcional da fila
from filaEncadeada import Queue

fila = Queue()
print(fila)
fila.push(1)
print(fila)
print(f"A posiçao do numero 1 na fila é {fila.get_index_value(1)}")
fila.push(10)
print(fila)
fila.push(30)
print(fila)
print(f"A posiçao do numero 30 na fila é {fila.get_index_value(30)}")
fila.pop()
print(fila)
fila.push(50)
print(fila)
fila.push(20)
print(fila)
fila.pop()
print(fila)
print(f"A posiçao do numero 30 na fila é {fila.get_index_value(30)}")